import Link from 'next/link'
import { addDirectMember, deleteParticipantData, mergeContacts } from '@/app/admin/actions'
import { requireAdmin } from '@/lib/admin/auth'
import { INDUSTRIES } from '@/lib/community/constants'
import { sanitizePostgrestSearch } from '@/lib/security'

export default async function ParticipantsPage({ searchParams }: { searchParams: Promise<{ industry?: string; location?: string }> }) {
  const filters = await searchParams
  const { service } = await requireAdmin()
  let query = service.from('community_participants').select('*').order('created_at',{ ascending: false }).limit(200)
  if (filters.industry) query = query.eq('industry', filters.industry)
  const location = filters.location ? sanitizePostgrestSearch(filters.location) : ''
  if (location) query = query.or(`country.ilike.%${location}%,city_region.ilike.%${location}%,us_state.ilike.%${location}%`)
  const { data: participants } = await query
  return <main className="admin-main"><header className="admin-heading"><div><p className="eyebrow">Participants</p><h1>Contacts and identities</h1><p>Filter subscriptions, merge a GitHub-only identity into an existing contact, or export the current filtered record safely.</p></div><Link className="admin-button" href={`/api/admin/participants/export?industry=${encodeURIComponent(filters.industry ?? '')}&location=${encodeURIComponent(filters.location ?? '')}`}>Export secure CSV</Link></header>
    <div className="admin-grid"><section className="admin-panel"><h2>Filter</h2><form className="admin-form" method="get"><label>Industry<select name="industry" defaultValue={filters.industry ?? ''}><option value="">All industries</option>{INDUSTRIES.map((industry) => <option key={industry}>{industry}</option>)}</select></label><label>Country, state, city, or region<input name="location" defaultValue={filters.location ?? ''} /></label><button type="submit">Apply filters</button></form></section><section className="admin-panel"><h2>Add an all-time member</h2><form className="admin-form" action={addDirectMember}><label>Identity type<select name="identity_kind"><option value="github">GitHub username</option><option value="email">Email</option></select></label><label>Identity<input name="identity_value" required /></label><label>Source<select name="source"><option value="github_contributor">Direct GitHub contributor</option><option value="director">Director</option><option value="core_contributor">Core Contributor</option><option value="manual">Manual</option></select></label><button>Add or match contact</button></form></section></div>
    <section className="admin-panel" style={{ marginTop:'1rem' }}><h2>Merge contacts</h2><p>Use the record to merge a GitHub-only contact into the person’s email contact. The historical count event remains, so the all-time total never decreases.</p><form className="admin-form" action={mergeContacts}><label>Source contact UUID<input name="source_contact_id" required /></label><label>Target contact UUID<input name="target_contact_id" required /></label><button>Merge identity and records</button></form></section>
    <div className="admin-table-wrap" style={{ marginTop:'1rem' }}><table className="admin-table"><thead><tr><th>Name / email</th><th>Industry</th><th>Location</th><th>Status</th><th>Contact ID</th><th>Action</th></tr></thead><tbody>{participants?.map((participant) => <tr key={participant.id}><td>{participant.name || '—'}<br /><small>{participant.email}</small></td><td>{participant.industry}{participant.industry_other ? ` — ${participant.industry_other}` : ''}</td><td>{[participant.city_region,participant.us_state,participant.country].filter(Boolean).join(', ')}</td><td><span className="status-badge">{participant.subscription_status}</span></td><td><code>{participant.contact_id}</code></td><td><form className="admin-form" action={deleteParticipantData}><input type="hidden" name="id" value={participant.id} /><label><span><input type="checkbox" name="confirm_delete" required /> Confirm irreversible personal-data deletion; the anonymous count remains.</span></label><button className="admin-button admin-button--quiet">Unsubscribe &amp; delete personal data</button></form></td></tr>)}</tbody></table>{!participants?.length ? <p className="admin-empty">No participant records match these filters.</p> : null}</div>
  </main>
}
