import type { Metadata } from 'next'

export const metadata: Metadata = { title: 'Privacy Policy', description: 'How Beneficence Protocol Foundation handles community and contribution information.' }

export default function PrivacyPage() {
  const contact = process.env.MONITORED_CONTACT_EMAIL ?? 'contact@beneficence.foundation'
  return <main id="main-content"><article className="legal-copy page-shell"><p className="eyebrow">Public implementation notice</p><h1>Privacy Policy</h1><div className="form-notice"><strong>Production approval required.</strong>This implementation describes the designed data flows. Community forms remain disabled until the organization approves the policy and configures every required service and contact channel.</div>
    <section><h2>Information we collect</h2><p>Community registration collects email, field or industry, region, consent records, and an optional name. Contributor applications additionally collect application choices, optional professional links, and profile-publication preference. Resource submissions collect contact details and information about a public URL. We never request a street address in these flows.</p></section>
    <section><h2>How we use information</h2><p>We use information to communicate about community activity, administer applications, review public resources, operate events through external registration services, enforce safety rules, maintain an audit record, and measure cumulative community growth. We do not treat registration as legal membership or sell these records.</p></section>
    <section><h2>AI-assisted processing</h2><p>Contributor application and resource-review workflows may use the OpenAI API. For applications, only participation reasons, contribution interests, related “Other” text, general location, and industry are sent. Email addresses and professional profile links are not sent, and the system does not crawl those links. Requests use a privacy-preserving hashed identifier and request <code>store: false</code>.</p><p>OpenAI states that API data is not used to train its models by default. Request content may nevertheless be retained in abuse-monitoring logs for up to 30 days, subject to the account’s applicable data controls. Meeting recordings, transcripts, or meeting contents are not sent to the Agent because the system does not create them.</p></section>
    <section><h2>Retention and the all-time count</h2><p>Closed applications that do not become Contributors are retained for 12 months, then names, emails, locations, links, application text, and Agent output are deleted. Community Participant information is retained until unsubscribe or a valid deletion request. Public People profiles are removed immediately when publication consent is withdrawn.</p><p>The all-time member count never decreases. When personal data is deleted, the system keeps only a non-identifying count event. If a deleted identity later submits again, the system may not be able to recognize the prior record.</p></section>
    <section><h2>Service providers and security</h2><p>Supabase provides database, authentication, and image storage; Resend provides transactional email; OpenAI provides administrative Agent processing; and external event platforms manage event registration and attendee data. Administrative access is restricted, exposed tables use row-level security, credentials stay server-side, and rate limits use short-lived HMAC-protected network buckets rather than raw IP addresses.</p></section>
    <section><h2>Your choices</h2><p>You may unsubscribe from community communication, request deletion or correction, or withdraw public-profile consent. Contact <a href={`mailto:${contact}`}>{contact}</a>. Legal or safety obligations may require limited retention, while the non-identifying cumulative count remains.</p></section>
  </article></main>
}
